---
- name: Install and configure topgrade
  ansible.builtin.import_role:
    name: _base_app
  vars:
    packages_pacman: []
    packages_apt: []
    packages_homebrew:
      - topgrade
    pre_stow_folders: []
    packages_stow:
      - topgrade

- name: Install tmux tools (Linux)
  ansible.builtin.include_tasks: tasks_linux.yml
  when: ansible_facts['distribution'] == 'Ubuntu' or ansible_facts['distribution'] == 'Archlinux'
